version: "3.8"

services:
  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password

  hazelcast:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast
    restart: always
    ports:
      - "5701:5701"

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
